#!/bin/bash
#
# Recursively build and tag docker images in a directory

set -eEuo pipefail

DEFAULT_DOCKER_CONTEXT_DIR=$(readlink -f "$(dirname "$0")")

usage() {
cat << EOF

  Recursively build and tag docker images in a directory
  Usage: $0 [OPTIONS]

  OPTIONS
  -h  Display this message and exit
  -d  Directory to find Dockerfiles/build contexts in [${DEFAULT_DOCKER_CONTEXT_DIR}]
  -c  Container registry
  -p  Also push built images

EOF
}

log() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&1
}

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

build_docker_image() {
  local dockerfile_path="$1"
  local docker_context_dir="$2"
  local -a build_args
  local env_file="${docker_context_dir}/build.env"

  if [[ -s "${env_file}" ]]; then
    nobuild=$(grep 'NOBUILD=true' "${env_file}" || true)
    if [[ -n "${nobuild}" ]]; then
      log "No-build set for docker context [${docker_context_dir}]; skipping"
      return
    fi
    while read -r build_arg || [[ -n "${build_arg}" ]]; do
      build_args+=(--build-arg "${build_arg}")
    done < "${env_file}"
  else
    err "No env file found for docker context [${docker_context_dir}]"
    err "Minimally define IMAGE_NAME=xxx and IMAGE_TAG=xxx in [${env_file}] and try again."
    exit 1
  fi

  local image_name
  image_name=$(grep 'IMAGE_NAME=' "${env_file}" || true)
  if [[ -z "${image_name}" ]]; then
    err "No IMAGE_NAME defined for docker context [${docker_context_dir}]"
    err "Set IMAGE_NAME in [${env_file}] and try again."
    exit 1
  else
    image_name=$(echo "${image_name}" | cut -d '=' -f 2)
  fi


  local image_tag
  image_tag=$(grep 'IMAGE_TAG=' "${env_file}" || true)
  if [[ -z "${image_tag}" ]]; then
    err "No IMAGE_TAG defined for docker context [${docker_context_dir}]"
    err "Set IMAGE_TAG in [${env_file}] and try again."
    exit 1
  else
    image_tag=$(echo "${image_tag}" | cut -d '=' -f 2)
  fi

  local tagged_image="${CONTAINER_REGISTRY:+"${CONTAINER_REGISTRY}/"}${image_name}:${image_tag}"
  log "Building ${tagged_image}"

  docker build \
    --rm \
    "${build_args[@]}" \
    -t "${tagged_image}" \
    -f "${dockerfile_path}" \
    "${docker_context_dir}"

  if [[ "${PUSH_IMAGES}" == 'true' ]]; then
    log "Pushing ${tagged_image}"
    docker push "${tagged_image}"
  fi
}

while getopts "hd:c:p" OPTION; do
  case $OPTION in
    h) usage; exit ;;
    d) DOCKER_CONTEXT_DIR=$OPTARG ;;
    c) CONTAINER_REGISTRY=$OPTARG;;
    p) PUSH_IMAGES='true' ;;
    \?) usage; exit ;;
  esac
done

DOCKER_CONTEXT_DIR=${DOCKER_CONTEXT_DIR:-"${DEFAULT_DOCKER_CONTEXT_DIR}"}
PUSH_IMAGES=${PUSH_IMAGES:-'false'}

readonly DOCKER_CONTEXT_DIR CONTAINER_REGISTRY PUSH_IMAGES

# Build regular docker images
while read -r dockerfile_path; do
  docker_context_dir=$(dirname "${dockerfile_path}")
  build_docker_image "${dockerfile_path}" "${docker_context_dir}"
done < <(find "${DOCKER_CONTEXT_DIR}" -type f -name Dockerfile)
